# Generated by Django 5.1.4 on 2024-12-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(max_length=255),
        ),
    ]
