# Generated by Django 5.1.4 on 2024-12-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0002_alter_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unique_code',
            field=models.CharField(blank=True, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
