# Generated by Django 5.1.4 on 2024-12-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0003_product_unique_code_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unique_code',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
