# Generated by Django 5.1.4 on 2025-01-02 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0004_alter_product_unique_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='weight',
            new_name='weight_or_quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unique_code',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
