# Generated by Django 5.1.5 on 2025-02-19 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0007_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(default='manfacturer', max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='id',
            field=models.CharField(blank=True, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
