# Generated by Django 5.1.5 on 2025-02-23 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0008_product_manufacturer_alter_offer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ourapp.offer'),
        ),
        migrations.AddField(
            model_name='order',
            name='redeemed_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
